version: '3.9'
services:
  smartroad-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  smartroad-frontend:
    build:
      context: ./smartroad-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://smartroad-backend:8080
    depends_on:
      - smartroad-backend
